<a href="https://colab.research.google.com/github/hasuhyeon/23python3gd/blob/main/ctab_7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. 일한시간과 시급을 계산하여 출력하는 코드

In [ ]:
hours_worked = int(input("일한시간을 입력하시오."))                              #사용자로부터 일한 시간을 입력받아 정수로 변환하여 hours_worked 변수에 저장합니다.
pay_rate = int(input("시급을 입력하시오.(23년 시급 9620):"))                     # 사용자로부터 시급을 입력받아 정수로 변환하여 pay_rate 변수에 저장합니다.
day_worked = int(input("일한날짜를 입력하시오. : "))                             # 사용자로부터 일한 날짜를 입력받아 정수로 변환하여 day_worked 변수에 저장합니다.
day_month = hours_worked * day_worked                                            # 일한 시간과 일한 날짜를 곱하여 day_month 변수에 저장합니다.
monthly_pay = hours_worked * pay_rate * day_worked                                # 일한 시간, 시급, 일한 날짜를 곱하여 월급여를 계산하여 monthly_pay 변수에 저장합니다.
print(f'일한시간은 {hours_worked}이며 시급은 (pay_rate)이고, 월급여는{monthly_pay}입니다.') # f-string을 사용하여 일한 시간, 시급, 월급여를 출력합니다.

일한시간을 입력하시오.10
시급을 입력하시오.(23년 시급 9620):9620
일한날짜를 입력하시오. : 25
일한시간은 10이며 시급은 (pay_rate)이고, 월급여는2405000입니다.


hours_worked = int(input("일한 시간을 입력하시오.: ")) : 사용자로부터 일한 시간을 입력받아 정수로 변환하여 hours_worked 변수에 저장합니다.
pay_rate = int(input("시급을 입력하시오.(23년 시급 9620): ")) : 사용자로부터 시급을 입력받아 정수로 변환하여 pay_rate 변수에 저장합니다.
day_worked = int(input("일한 날짜를 입력하시오.: ")) : 사용자로부터 일한 날짜를 입력받아 정수로 변환하여 day_worked 변수에 저장합니다.
day_month = hours_worked * day_worked : 일한 시간과 일한 날짜를 곱하여 day_month 변수에 저장합니다.
monthly_pay = hours_worked * pay_rate * day_worked : 일한 시간, 시급, 일한 날짜를 곱하여 월급여를 계산하여 monthly_pay 변수에 저장합니다.
print(f'일한 시간은 {hours_worked}이며 시급은 {pay_rate}이고, 월급여는 {monthly_pay}입니다.') : f-string을 사용하여 일한 시간, 시급, 월급여를 출력합니다.

2. 환전하는 코드를 작성
- 변수 won, usd, exchange

- 계산won*usd

In [ ]:
won = int(input("환전할 금액을 입력:"))                                          # 사용자로부터 환전할 금액을 입력받아 정수로 변환하여 won 변수에 저장합니다.
usd = int (input("달러의 환율 금액 입력 (231031: 1372원)"))                      # 사용자로부터 달러의 환율 금액을 입력받아 정수로 변환하여 usd 변수에 저장합니다.
exchange = won *usd                                                              # 환전할 금액과 환율을 곱하여 exchange 변수에 저장합니다.
print(exchange)                                                                  # exchange 값을 출력합니다.


환전할 금액을 입력:2000
달러의 환율 금액 입력 (231031: 1372원)1372
2744000


won = int(input("환전할 금액을 입력하세요: ")) : 사용자로부터 환전할 금액을 입력받아 정수로 변환하여 won 변수에 저장합니다.
usd = int(input("달러의 환율 금액을 입력하세요 (231031: 1372원): ")) : 사용자로부터 달러의 환율 금액을 입력받아 정수로 변환하여 usd 변수에 저장합니다.
exchange = won * usd : 환전할 금액과 환율을 곱하여 exchange 변수에 저장합니다.
print(exchange) : exchange 값을 출력합니다.

3. 화씨를 섭씨로 섭씨를 화싸로 변경하는 코드
- 화씨를 섭씨로 "F = ℃* 1.8+32
-섭씨를 화씨로 "℃=('F-32) / 1.8
-변수 화씨 fahrenheit, 섭씨 celsius


In [ ]:
fahrenheit = int(input("화씨를 입력하시오.:"))                                   # 사용자로부터 화씨 온도를 입력받아 정수로 변환하여 fahrenheit 변수에 저장합니다.
celsius = (fahrenheit - 32) / 1.8                                                # 사용자로부터 화씨 온도를 입력받아 정수로 변환하여 fahrenheit 변수에 저장합니다.
print(celsius)                                                                   # celsius 값을 출력합니다.

화씨를 입력하시오.:100
37.77777777777778


fahrenheit = int(input("화씨를 입력하시오.: ")) : 사용자로부터 화씨 온도를 입력받아 정수로 변환하여 fahrenheit 변수에 저장합니다.
celsius = (fahrenheit - 32) / 1.8 : 입력받은 화씨 온도를 섭씨 온도로 변환하여 celsius 변수에 저장합니다.
print(celsius) : celsius 값을 출력합니다.

In [ ]:
celsius = float(input("섭씨를 입력하시오.:"))                                    # 사용자로부터 섭씨 온도를 입력받아 실수로 변환하여 celsius 변수에 저장합니다.
fahrenheit = celsius * 1.8 +32                                                   # 사용자로부터 섭씨 온도를 입력받아 실수로 변환하여 celsius 변수에 저장합니다.
print(fahrenheit)                                                                # fahrenheit 값을 출력합니다.

섭씨를 입력하시오.:37.77777777777778
100.0


celsius = float(input("섭씨를 입력하시오.: ")) : 사용자로부터 섭씨 온도를 입력받아 실수로 변환하여 celsius 변수에 저장합니다.
fahrenheit = celsius * 1.8 + 32 : 입력받은 섭씨 온도를 화씨 온도로 변환하여 fahrenheit 변수에 저장합니다.
print(fahrenheit) : fahrenheit 값을 출력합니다.